theme: jekyll-theme-hacker
title: MostlyWhat's Repository
show_downloads: true
description: [A short description of your blog's purpose]
url: [Canonical URL for this blog]
author:
  name: MostlyWhat
  email: admin@mostlywhat.space
  url: mostlywhat.space
